server:
  port: 9852
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enable: true
      # 最大单个文件大小
      max-file-size: 10MB
      # 整个请求最大大小(可多文件)
      max-request-size: 10MB
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${data.datasource.driver-class-name}
      # url: jdbc:mysql://${data.datasource.host}:${data.datasource.port}/${data.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8mb4&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      url: jdbc:mysql://${data.datasource.host}:${data.datasource.port}/${data.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${data.datasource.username}
      password: ${data.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.data.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      data:
        mapper: debug
        service: info
        controller: info

data-element:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: yexca
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 用户端
    user-secret-key: lemon
    user-ttl: 7200000
    user-token-name: token
  alioss:
    access-key-id: ${data.alioss.access-key-id}
    access-key-secret: ${data.alioss.access-key-secret}
    bucket-name: ${data.alioss.bucket-name}
    endpoint: ${data.alioss.endpoint}
  elastic-search:
    server: ${data.elastic-search.server}
  fisco-ecos:
    config-file: src/main/resources/config-example.toml
    abi-file-path: src/main/resources/abi/
    bin-file-path: ""